import {Header,Footer} from '@/components/chrome';
export const metadata={title:'Quick start'};
export default function Guide() {
  return <><Header/><main id="main" className="content-page page-width"><span className="eyebrow">LESS SETUP. MORE SHOWING.</span><h1>Your first recording.</h1><div className="prose">
    <p>Start with the free desktop preview from <a href="/download">Downloads</a>. No payment or license is needed for Free.</p>
    <section className="guide-section"><h2>1. Give Focus permission</h2><p>On macOS, allow Screen Recording access. If you previously denied access, open System Settings → Privacy & Security → Screen & System Audio Recording, enable Focus Recorder, then reopen it.</p>
      <h2>2. Pick your screen</h2><p>Choose a display and 720p or 1080p quality. Free recordings use 24 fps and include a bouncing watermark for the entire exported video. On Mac, turn system audio on if your walkthrough needs it.</p>
      <h2>3. Find the right amount of focus</h2><p>Enable automatic zoom. The Strength slider changes how close the camera gets. A smaller value leaves more of the screen visible; a larger value brings small details forward. Cursor smoothing works on the recorded pointer independently of this setting. Both are included in Free.</p>
      <h2>4. Record your story</h2><p>Choose where to save your movie and begin recording. Two nearby clicks trigger a zoom on Mac. Move through your demonstration naturally; the recorded cursor eases through navigation and stays aligned with clicks. The moving watermark is added only to exported video.</p>
      <h2>5. Stop and share</h2><p>On Mac, use the menu bar or <code>Shift–Command–R</code> to stop. If another app owns that shortcut, use Focus’s own controls. The finished QuickTime movie is saved locally to your chosen destination.</p>
    </section>
    <section id="windows" className="guide-section"><h2>Windows quick start</h2><p>Install the separate Windows 10 / 11 x64 preview, pick a display, and choose 720p or 1080p. Enable microphone recording if you want narration. Choose a WebM destination, start recording, and use the app’s Stop control to finish. Leave the app open while it finishes writing your file.</p><p>Free uses 24 fps with the moving watermark. Pro supports 30 fps without a watermark. Windows does not yet support system audio, MP4, 1440p, or 60 fps. This is an unsigned preview; see the distribution notes on <a href="/download">Downloads</a>.</p></section>
    <section id="pro" className="guide-section"><h2>Unlocking Pro — $9 USD per month</h2><p>Pro removes the export watermark and unlocks the paid quality settings supported by your computer. Each subscription activates one device; device swaps are not supported. Try Free first to check recording, export, and preview compatibility on your device.</p><ol><li>On Mac, open the license activation window and choose <strong>Copy ID</strong>. On Windows, expand <strong>Activate Pro</strong> and select and copy the <strong>Device ID</strong> field.</li><li>Open <a href="/checkout">Focus Pro checkout</a>, choose your platform, and paste that Device ID. Read the subscription terms and check the consent box. If checkout is unavailable, you can keep using Free.</li><li>Continue to PayPal and approve the $9 USD monthly subscription. There is no free trial. Keep the return page open in the same browser while payment is verified.</li><li>Copy or download the activation token from the confirmation page. Paste it into the Mac license activation window. On Windows, paste it into <strong>Pro license</strong> and choose <strong>Activate Pro on this device</strong>.</li></ol><p>Connect the app to the internet at least every three days so it can refresh your activation while the subscription is paid. Without a valid activation, Free remains available at up to 1080p and 24 fps, with a bouncing watermark throughout exported video.</p><h2>Managing your subscription</h2><p>PayPal automatically charges $9 USD each month until you cancel in your PayPal account. Cancelling stops future renewals and retains access through the current paid period. Refunds or payment disputes can revoke access earlier.</p><p>If confirmation is delayed, use <strong>Check payment again</strong> on the return page. Check PayPal before starting another subscription to avoid a duplicate purchase. A visit to the return page, a PayPal approval alone, or a <a href="/checkout/demo">simulation receipt</a> does not activate Pro; payment must be verified first.</p></section>
  </div></main><Footer/></>;
}
