import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Check, Monitor, MousePointer2, MoveUpRight, Play, Scan, ShieldCheck, WandSparkles, Video, Download } from 'lucide-react';
import { Header, Footer } from '@/components/chrome';
import { ProductDemo } from '@/components/product-demo';
import { ApplePlatformIcon, WindowsPlatformIcon } from '@/components/platform-icons';

const faqs = [
  ['What does automatic zoom do?', 'Focus Recorder moves the camera closer to the action. On macOS, two nearby clicks trigger a smooth zoom that follows your cursor, holds briefly, and eases back out. The Strength setting controls how far it zooms in.'],
  ['Does smoother movement change my actual mouse?', 'Your real pointer responds normally. The recorder smooths and limits cursor travel in the exported video. Clicks stay aligned with the actual action so the recording is easy to follow.'],
  ['What is included for free?', 'Download and record without an account or license. Free includes automatic zoom, cursor smoothing, 720p or 1080p, and 24 fps. Every exported video has a Focus Recorder watermark that slowly bounces around for its entire duration. The watermark is added only to exported video.'],
  ['What does Pro unlock?', 'Focus Pro is $9 USD per month and follows your account, not a Device ID. Sign into the app to unlock watermark-free exports. Mac also supports 1440p and 30 / 60 fps; the Windows preview supports up to 1080p at 30 fps. Connect at least every three days to refresh access while your subscription is paid.'],
  ['Can I use Focus Recorder on Windows?', 'Yes, a separate Windows 10 / 11 x64 desktop preview is available as a free download. It includes native Windows capture, automatic zoom, cursor smoothing, optional microphone audio, and local WebM export. Mac requires macOS 15 or later on Apple silicon. See Downloads for preview signing and feature differences.'],
  ['Where do my recordings go?', 'Recordings are saved to the destination you choose on your computer. The recorder does not upload your screen to this website.'],
  ['How do payments and cancellation work?', 'When subscriptions are available, checkout takes you to PayPal to approve $9 USD per month. It renews automatically until you cancel in PayPal, with no free trial. Cancellation keeps access through your current paid period; a refund or payment dispute can revoke it earlier. Checkout shows its availability before you can start a payment.'],
];
export default function Home() { return <><Header/><main id="main">
  <section className="hero page-width"><span className="eyebrow"><span className="orange-dot"/> A SMALL TOOL. A BIG DIFFERENCE.</span><h1>Your screen.<br/>A little more <span className="word-cinematic">cinematic<svg viewBox="0 0 380 15" aria-hidden="true"><path d="M3 11C88 1 230 1 376 6"/></svg></span>.</h1><p className="hero-description">Turn everyday screen recordings into something worth watching.<br className="desktop-break"/> Smooth zooms. Effortless cursor movement. All done for you.</p><div className="hero-actions"><Link href="/download" className="button button-orange"><Download size={18}/> Get Focus Recorder <ArrowUpRight size={16}/></Link><a href="#demo" className="button button-plain"><span className="play-outline"><Play size={12} fill="currentColor"/></span>See it in motion</a></div><div className="hero-meta"><span><ApplePlatformIcon size={12}/> Built for macOS</span><i/><span><WindowsPlatformIcon size={13}/> Windows preview</span><i/><span>No cloud uploads</span></div><ProductDemo/><div className="demo-under"><span>Less “wait, where did you click?”</span><span>More “oh, I get it.” <MoveUpRight size={20}/></span></div></section>
  <section id="features" className="features page-width"><div className="section-head"><div><span className="eyebrow">THE GOOD STUFF, AUTOMATICALLY</span><h2>Focus on your story.<br/>We’ll follow your lead.</h2></div><p>A polished walkthrough shouldn’t need<br/>an afternoon in an editing app.</p></div><div className="feature-grid"><article className="feature-card"><span className="feature-icon"><Scan size={24}/></span><h3>Zoom with intention.</h3><p>Bring the details closer, right when they matter. Automatic zoom follows the action and gently pulls back.</p><div className="zoom-visual" aria-hidden="true"><div className="mini-lines"><i/><i/><i/></div><div className="zoom-box"><MousePointer2 size={23} fill="currentColor"/><span>1.75×</span></div><span className="visual-label">JUST THE RIGHT AMOUNT OF CLOSE.</span></div></article><article className="feature-card"><span className="feature-icon"><MousePointer2 size={24}/></span><h3>Every move, smoother.</h3><p>Fast navigation becomes a calm, easy-to-follow path. Your clicks stay exactly where they belong.</p><div className="cursor-visual" aria-hidden="true"><svg viewBox="0 0 320 110"><path className="rough-path" d="M5 70L30 40L58 75L86 29L120 67L150 15L200 68L228 28L270 40L311 14"/><path className="smooth-path" d="M5 90C90 110 75 10 163 40S234 75 305 24"/></svg><MousePointer2 size={22} fill="currentColor"/><span className="visual-label">A LITTLE LESS CHAOS. A LOT MORE FLOW.</span></div></article><article className="feature-card"><span className="feature-icon"><ShieldCheck size={24}/></span><h3>Your screen stays yours.</h3><p>Capture and export on your computer. Your ideas, drafts, and recordings stay in your hands.</p><div className="private-visual" aria-hidden="true"><div className="local-folder"><FolderIcon/></div><span className="file-label"><Video size={14}/> my-next-big-thing.mov <Check size={14}/></span><span className="visual-label">SAVED LOCALLY. READY TO SHARE.</span></div></article></div></section>
  <section className="workflow-wrap" id="how-it-works"><div className="workflow page-width"><div className="workflow-heading"><span className="eyebrow">FROM “LET ME SHOW YOU” TO DONE</span><h2>Hit record.<br/>Find your flow.</h2><Link href="/guide" className="text-link">Your two-minute quick start <ArrowUpRight size={17}/></Link></div><div className="workflow-steps">{[[Monitor,'Pick your screen.','Choose a display and your recording quality.'],[MousePointer2,'Do your thing.','Walk through your idea. Focus follows the action.'],[Video,'Make it a movie.','Save a finished recording, ready for its audience.']].map(([Icon,title,body],i)=>{const I=Icon as typeof Monitor;return <div className="workflow-step" key={i}><span className="step-number">0{i+1}</span><div><h3>{title as string}</h3><p>{body as string}</p></div><I size={22}/></div>})}</div></div></section>
  <section id="pricing" className="pricing page-width">
    <div className="section-head centered"><span className="eyebrow">YOUR NEXT GREAT DEMO STARTS FREE</span><h2>Start free. Make it your own.</h2><p>The essentials are yours. Unlock clean, higher-frame-rate exports with Pro.</p></div>
    <div className="pricing-grid">
      <article className="price-card"><span className="plan-kicker">FOR YOUR EVERYDAY IDEAS</span><h3>Focus Free</h3><p>Record your next walkthrough.<br/>No account. No payment. No time limit.</p><div className="price">$0<span> / always</span></div><span className="price-note">Free desktop preview · macOS & Windows</span><Link href="/download" className="button button-dark">Download free <ArrowUpRight size={16}/></Link><ul><li><Check/>720p / 1080p at 24 fps</li><li><Check/>Automatic zoom & cursor smoothing</li><li><Check/>Local recording and export</li><li><Check/>Bouncing watermark throughout the video</li></ul></article>
      <article className="price-card price-featured"><span className="plan-kicker">A CLEANER FINISH FOR YOUR STORY</span><h3>Focus Pro <span>YOUR ACCOUNT</span></h3><p>Higher frame rates.<br/>Your work, without the watermark.</p><div className="price">$9<span> USD / month</span></div><span className="price-note">Renews monthly · cancel in PayPal · no free trial</span><Link href="/checkout" className="button button-orange">Get Focus Pro <ArrowUpRight size={16}/></Link><ul><li><Check/>Watermark-free exports</li><li><Check/>Mac: up to 1440p and 60 fps</li><li><Check/>Windows: up to 1080p and 30 fps</li><li><Check/>Account login · no Device ID required</li></ul></article>
    </div><p className="checkout-note">Sign in and approve your subscription with <b>PayPal</b> when checkout is available. Cancel any time; keep the current paid period. Refunds or disputes can revoke access. Connect the app at least every three days to refresh Pro.</p>
  </section>
  <section className="faq page-width"><div><span className="eyebrow">A FEW THINGS YOU MIGHT WONDER</span><h2>Good questions.</h2><p>Let’s clear up the little details.</p></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="closing page-width"><div className="closing-mark"><WandSparkles size={29}/></div><span className="eyebrow">READY WHEN YOU ARE</span><h2>Show it.<br/>Make it click.</h2><Link href="/download" className="button button-orange">Meet your new recorder <ArrowRight size={17}/></Link><p>Less editing. More creating.</p></section>
  </main><Footer/></> }
function FolderIcon(){return <svg width="86" height="70" viewBox="0 0 86 70" fill="none"><path d="M6 12a6 6 0 0 1 6-6h21l8 9h33a6 6 0 0 1 6 6v40H6V12Z" fill="#d4b579"/><rect x="6" y="23" width="74" height="40" rx="5" fill="#e9d19e"/><path d="m34 42 6 6 13-14" stroke="#7a612f" strokeWidth="3" strokeLinecap="round"/></svg>}
