import { Header, Footer } from '@/components/chrome';

export const metadata = { title: 'Privacy and subscription details' };

export default function Privacy() {
  return <><Header /><main id="main" className="content-page page-width"><span className="eyebrow">CLEAR BY DESIGN</span><h1>Your work stays yours.</h1><div className="prose">
    <h2>Desktop recordings</h2><p>Focus Recorder captures and renders on your computer. Screen recordings are saved locally and are not uploaded to this website. You choose what to share and where to send the exported file.</p>
    <h2>This website</h2><p>The website does not request camera, microphone, or screen access. We have not added advertising trackers, analytics scripts, or marketing cookies. Netlify hosts the website and may process request metadata, such as IP addresses and user agents, to operate and protect its service.</p>
    <h2>Your account</h2><p>Google Firebase Authentication handles registration, email verification, passwords, and login sessions. See <a href="https://firebase.google.com/support/privacy">Firebase’s privacy and security information</a>. Your email and authentication requests are sent to the Focus Recorder Firebase project; Firebase also processes request metadata to operate the service and prevent abuse. Our payment service independently verifies your login and email verification with Firebase and uses a project-scoped account identifier to associate your subscription. Your email address and editable profile fields are not proof of payment.</p><p>The website keeps its login session in browser storage so you remain signed in. When persistent storage is unavailable, the session may last only for that tab. Sign out on shared computers. Verification and password changes are completed through Firebase’s secure email action pages. The desktop app keeps session credentials in macOS Keychain or an encrypted Windows application file. Your password is not saved by the app. Signing out clears that app’s account session and account-based Pro access.</p>
    <h2>PayPal checkout</h2><p>When checkout is available, Focus Pro costs $9 USD per month for your account. You review and approve the subscription on PayPal’s website. PayPal processes payment details under its <a href="https://www.paypal.com/privacy">privacy policy</a>. This website does not request or store card numbers or your PayPal password.</p><p>Our service stores your Firebase project-scoped account identifier, subscription and payment identifiers, subscription status, and paid-period information. These records let us verify payment and handle cancellation, refunds, or disputes. New subscriptions do not collect a hardware Device ID or bind Pro to a computer.</p><p>An essential, secure checkout session cookie protects checkout requests and cannot be read by page scripts. Older device-based purchases retain their original hashed Device ID and platform records for continued verification; they are not automatically assigned to a login. Legacy activation tokens can still be copied or downloaded from their original confirmation session. Keep those files private.</p>
    <h2>Desktop activation and renewal</h2><p>The app verifies a signed, short-lived activation associated with the signed-in account. It contacts the licensing service to refresh access while your subscription is paid. Connect at least every three days; if valid activation expires, the app returns to Free until access is verified again. Older manual licenses retain their existing verification rules. Activation and renewal do not upload your recordings.</p>
    <h2>Subscription terms</h2><p>The price is $9 USD per month, automatically renewed until you cancel in PayPal. There is no free trial. New subscriptions follow your account and do not have a device-swap lock. Cancelling stops future renewals and keeps Pro available through the current paid period. Refunds or payment disputes can revoke access earlier. Signing out does not cancel a subscription.</p>
    <h2>Checkout simulation</h2><p>The separate <a href="/checkout/demo">checkout demo</a> is a local simulation with illustrative Stripe and PayPal options. It does not contact either payment provider, charge money, or issue an activation license. Requests contain only a demo plan, provider, and result scenario.</p>
    <h2>Preview releases</h2><p>Free is available without an account or payment, at up to 1080p and 24 fps. A Focus Recorder watermark bounces throughout the exported video and is added at export. Installer signing, supported formats, and Windows testing status are described on the <a href="/download">Downloads page</a>. Try your device before subscribing.</p>
    <h2>Public source</h2><p>The website and documentation are published in a <a href="https://github.com/heinrichryodigital/focus-recorder">limited public repository</a>. The desktop recorder engine, release automation, and license issuer are kept private.</p>
  </div></main><Footer /></>;
}
