import { Header, Footer } from '@/components/chrome';

export const metadata = { title: 'Privacy and subscription details' };

export default function Privacy() {
  return <><Header /><main id="main" className="content-page page-width"><span className="eyebrow">CLEAR BY DESIGN</span><h1>Your work stays yours.</h1><div className="prose">
    <h2>Desktop recordings</h2><p>Focus Recorder captures and renders on your computer. Screen recordings are saved locally and are not uploaded to this website. You choose what to share and where to send the exported file.</p>
    <h2>This website</h2><p>The website does not request camera, microphone, or screen access. We have not added advertising trackers, analytics scripts, or marketing cookies. Netlify hosts the website and may process request metadata, such as IP addresses and user agents, to operate and protect its service.</p>
    <h2>PayPal checkout</h2><p>When checkout is available, Focus Pro costs $9 USD per month for one device. You review and approve the subscription on PayPal’s website. PayPal collects and processes your payment details under its own <a href="https://www.paypal.com/privacy">privacy policy</a>. This website does not request or store card numbers or your PayPal password.</p><p>To fulfil your subscription, our service stores the minimum subscription and payment identifiers, a hashed Device ID, your selected platform, and subscription status and paid-period information. These records let us verify payment, issue activation, and handle cancellation, refunds, or disputes.</p><p>An essential, secure checkout session cookie associates your browser with your checkout. It cannot be read by page scripts. Activation tokens are kept in the page’s memory for copying or downloading, not in browser local storage. A downloaded token remains in the file you save; keep it private.</p>
    <h2>Desktop activation and renewal</h2><p>The app verifies a signed activation associated with your hashed Device ID. It contacts the licensing service to renew access while your subscription is paid. Connect at least every three days; if valid activation expires, the app returns to Free until access is verified again. Activation and renewal do not upload your recordings.</p>
    <h2>Subscription terms</h2><p>The price is $9 USD per month, automatically renewed until you cancel in PayPal. There is no free trial. Each subscription is for one device; device swaps are not supported. Cancelling stops future renewals and keeps Pro available through the current paid period. Refunds or payment disputes can revoke access earlier.</p>
    <h2>Checkout simulation</h2><p>The separate <a href="/checkout/demo">checkout demo</a> is a local simulation with illustrative Stripe and PayPal options. It does not contact either payment provider, charge money, or issue an activation license. Requests contain only a demo plan, provider, and result scenario.</p>
    <h2>Preview releases</h2><p>Free is available without an account or payment, at up to 1080p and 24 fps. A Focus Recorder watermark bounces throughout the exported video and is added at export. Installer signing, supported formats, and Windows testing status are described on the <a href="/download">Downloads page</a>. Try your device before subscribing.</p>
    <h2>Public source</h2><p>The website and documentation are published in a <a href="https://github.com/heinrichryodigital/focus-recorder">limited public repository</a>. The desktop recorder engine, release automation, and license issuer are kept private.</p>
  </div></main><Footer /></>;
}
